In [1]:
# Hierarchical Indexing

In [2]:
import pandas as pd
import numpy as np

In [3]:
data = pd.Series(np.random.randn(9),
index=[['a','a','a','b','b','c','c','d','d'],
[1,2,3,1,3,1,2,2,3]])

In [4]:
data

a  1    1.546783
   2    0.515167
   3    1.188362
b  1   -0.212491
   3    0.146130
c  1    1.357019
   2    0.038024
d  2    0.535710
   3    1.342479
dtype: float64

In [5]:
data.index

MultiIndex([('a', 1),
            ('a', 2),
            ('a', 3),
            ('b', 1),
            ('b', 3),
            ('c', 1),
            ('c', 2),
            ('d', 2),
            ('d', 3)],
           )

In [6]:
data['b']

1   -0.212491
3    0.146130
dtype: float64

In [7]:
data['b':'c']

b  1   -0.212491
   3    0.146130
c  1    1.357019
   2    0.038024
dtype: float64

In [8]:
data.loc[['b','d']]

b  1   -0.212491
   3    0.146130
d  2    0.535710
   3    1.342479
dtype: float64

In [9]:
data.loc[:,2]

a    0.515167
c    0.038024
d    0.535710
dtype: float64

In [10]:
data.unstack()

1         2         3
a  1.546783  0.515167  1.188362
b -0.212491       NaN  0.146130
c  1.357019  0.038024       NaN
d       NaN  0.535710  1.342479

In [11]:
data.unstack().stack()

a  1    1.546783
   2    0.515167
   3    1.188362
b  1   -0.212491
   3    0.146130
c  1    1.357019
   2    0.038024
d  2    0.535710
   3    1.342479
dtype: float64

In [12]:
data

a  1    1.546783
   2    0.515167
   3    1.188362
b  1   -0.212491
   3    0.146130
c  1    1.357019
   2    0.038024
d  2    0.535710
   3    1.342479
dtype: float64

In [13]:
data.unstack()

1         2         3
a  1.546783  0.515167  1.188362
b -0.212491       NaN  0.146130
c  1.357019  0.038024       NaN
d       NaN  0.535710  1.342479

In [14]:
data

a  1    1.546783
   2    0.515167
   3    1.188362
b  1   -0.212491
   3    0.146130
c  1    1.357019
   2    0.038024
d  2    0.535710
   3    1.342479
dtype: float64

In [15]:
frame = pd.DataFrame(np.arange(12).reshape((4,3)),
index=[['a','a','b','b'],[1,2,1,2]],
columns=[['Ohio','Ohio','Colorado'],['Green','Red','Green']])

In [16]:
frame

Ohio     Colorado
    Green Red    Green
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11

In [17]:
# Indexing with a DataFrame's columns

In [22]:
frame = pd.DataFrame({'a': range(7),'b': range(7,0,-1),'c':['one','one','one','two','two','two','two'],'d': [0,1,2,0,1,2,3]})

In [23]:
frame

a  b    c  d
0  0  7  one  0
1  1  6  one  1
2  2  5  one  2
3  3  4  two  0
4  4  3  two  1
5  5  2  two  2
6  6  1  two  3

In [24]:
# set index function will create a new DataFrame using one of its columns as the index

In [25]:
frame2 = frame.set_index(['c','d'])

In [26]:
frame2

a  b
c   d      
one 0  0  7
    1  1  6
    2  2  5
two 0  3  4
    1  4  3
    2  5  2
    3  6  1

In [27]:
frame.set_index(['c','d'], drop=False)

a  b    c  d
c   d              
one 0  0  7  one  0
    1  1  6  one  1
    2  2  5  one  2
two 0  3  4  two  0
    1  4  3  two  1
    2  5  2  two  2
    3  6  1  two  3

In [28]:
frame2.reset_index()

c  d  a  b
0  one  0  0  7
1  one  1  1  6
2  one  2  2  5
3  two  0  3  4
4  two  1  4  3
5  two  2  5  2
6  two  3  6  1

In [29]:
# Combining and Merging DataSets

In [30]:
# - Database-Style DataFrame JOins

In [31]:
df1 = pd.DataFrame({'key': ['b','b','a','c','a','a','b'], 'data1': range(7)})

In [32]:
df1

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6

In [33]:
df2 = pd.DataFrame({'key':['a','b','d'], 'data2': range(3)})

In [34]:
df2

key  data2
0   a      0
1   b      1
2   d      2

In [37]:
pd.merge(df1,df2, on= 'key')

key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0

In [36]:
df1

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6

In [38]:
df3 = ({'key': ['b','b','a','c','a','a','b'], 'data1': range(7)})

In [39]:
df3

{'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'], 'data1': range(0, 7)}

In [42]:
df3 = pd.DataFrame(df3)

In [43]:
df3

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6

In [44]:
df4 = ({'rkey': ['a','b','d'], 'data2': range(3)})

In [45]:
df4 = pd.DataFrame(df4)

In [46]:
df4

rkey  data2
0    a      0
1    b      1
2    d      2

In [47]:
df3

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6

In [49]:
pd.merge(df3,df4, left_on = 'key',right_on='rkey')

key  data1 rkey  data2
0   b      0    b      1
1   b      1    b      1
2   b      6    b      1
3   a      2    a      0
4   a      4    a      0
5   a      5    a      0

In [50]:
pd.merge(df1, df2, how = 'outer')

key  data1  data2
0   b    0.0    1.0
1   b    1.0    1.0
2   b    6.0    1.0
3   a    2.0    0.0
4   a    4.0    0.0
5   a    5.0    0.0
6   c    3.0    NaN
7   d    NaN    2.0

In [51]:
df1 = pd.DataFrame({'key': ['b','b','a','c','a','b'], 
'data1': range(6)})

In [52]:
df2 = pd.DataFrame({'key': ['a','b','a','b','d'],
'data2': range(5)})

In [53]:
df1

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [54]:
df2

key  data2
0   a      0
1   b      1
2   a      2
3   b      3
4   d      4

In [55]:
pd.merge(df1,df2, on='key',how='left')

key  data1  data2
0    b      0    1.0
1    b      0    3.0
2    b      1    1.0
3    b      1    3.0
4    a      2    0.0
5    a      2    2.0
6    c      3    NaN
7    a      4    0.0
8    a      4    2.0
9    b      5    1.0
10   b      5    3.0

In [56]:
pd.merge(df1,df2,how='inner')

key  data1  data2
0   b      0      1
1   b      0      3
2   b      1      1
3   b      1      3
4   b      5      1
5   b      5      3
6   a      2      0
7   a      2      2
8   a      4      0
9   a      4      2

In [57]:
# to marge with multiple keys

In [58]:
left = pd.DataFrame({'key1': ['foo','foo','bar'],
                    'key2': ['one','two','one'],
                    'lval': [1,2,3]})

In [59]:
right = pd.DataFrame({'key1': ['foo','foo','bar','bar'],
                        'key2': ['one','one','one','two'],
                        'rval': [4,5,6,7]})

In [60]:
left

key1 key2  lval
0  foo  one     1
1  foo  two     2
2  bar  one     3

In [61]:
right

key1 key2  rval
0  foo  one     4
1  foo  one     5
2  bar  one     6
3  bar  two     7

In [64]:
pd.merge(left,right, on=['key1','key2'], how='outer')

key1 key2  lval  rval
0  foo  one   1.0   4.0
1  foo  one   1.0   5.0
2  foo  two   2.0   NaN
3  bar  one   3.0   6.0
4  bar  two   NaN   7.0

In [65]:
pd.merge(left,right,on='key1')

key1 key2_x  lval key2_y  rval
0  foo    one     1    one     4
1  foo    one     1    one     5
2  foo    two     2    one     4
3  foo    two     2    one     5
4  bar    one     3    one     6
5  bar    one     3    two     7

In [66]:
pd.merge(left,right, on='key1',suffixes=('_left','_right'))

key1 key2_left  lval key2_right  rval
0  foo       one     1        one     4
1  foo       one     1        one     5
2  foo       two     2        one     4
3  foo       two     2        one     5
4  bar       one     3        one     6
5  bar       one     3        two     7

In [67]:
# Marging on Index

In [68]:
left1 = pd.DataFrame({'key': ['a','b','a','a','b','c'], 'value': range(6)})

In [69]:
right1 = pd.DataFrame({'group_val':[3.5,7]}, index=['a','b'])

In [70]:
left1

key  value
0   a      0
1   b      1
2   a      2
3   a      3
4   b      4
5   c      5

In [71]:
right1

group_val
a        3.5
b        7.0

In [72]:
pd.merge(left1,right1,left_on='key',right_index=True)

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0

In [73]:
pd.merge(left1,right1,left_on='key',right_index=True, how='outer')

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0
5   c      5        NaN

In [74]:
# Concatenating Along an Axis

In [75]:
arr = np.arange(12).reshape((3,4))

In [76]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [77]:
np.concatenate([arr,arr], axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [79]:
# Concatenating Indexes

In [80]:
s1 = pd.Series([0,1], index=['a','b'])
s2 = pd.Series([2,3,4], index=['c','d','e'])
s3 = pd.Series([5,6], index=['f','g'])

In [81]:
s1

a    0
b    1
dtype: int64

In [82]:
s2

c    2
d    3
e    4
dtype: int64

In [83]:
s3

f    5
g    6
dtype: int64

In [85]:
pd.concat([s1,s2,s3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [86]:
pd.concat([s1,s2,s3], axis=1)

0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

In [87]:
s4 = pd.concat([s1,s3])

In [88]:
s4

a    0
b    1
f    5
g    6
dtype: int64

In [89]:
pd.concat([s1,s4], axis=1)

0  1
a  0.0  0
b  1.0  1
f  NaN  5
g  NaN  6

In [90]:
pd.concat([s1,s4],axis=1, join='inner')

0  1
a  0  0
b  1  1